### ISSUE TITLE
Remove Download from lightbox

### ISSUE THREAD

**Issue by Fendavo** [andrewhancox/Moodle-jQuery-Lightbox-Gallery#10]
This is an awesome plugin.

I have a low-priority request. There is no permission to remove the "DOWNLOAD" option under the 'CLOSE' icon when an image is clicked on from the gallery. Example here:
https://www.tituslearning.com/wp-content/uploads/2017/10/imsge2.png

I realise that if the link was removed, then users could simply right-click on the image anyway, to download it, but in our educational institution I'd like to be able to remove that temptation from the lightbox to minimise students stealing images that another student has created. Then only those students who seriously want the picture will 'right-click' to download it. 

There would be still be situations where I'd like to see the 'DOWNLOAD', so I think I'm asking for a permission setting at the activity level so that it can be changed to 'allow' or disallow as required for different lightbox galleries in our course.

Thanks in advance for anything that can be done for this

**Comment by Fendavo** [comment]
![image](https://user-images.githubusercontent.com/38377785/55051465-efd1bc00-50a0-11e9-8d81-4d4900fa269a.png)

**Comment by Fendavo** [comment]
Becomes this if the permission 'Display Download link in lightbox' is set to "NO"
![image](https://user-images.githubusercontent.com/38377785/55051510-27d8ff00-50a1-11e9-9963-4150e1a98f9d.png)

**Comment by AranWS** [comment]
> Becomes this if the permission 'Display Download link in lightbox' is set to "NO" ![image](https://user-images.githubusercontent.com/38377785/55051510-27d8ff00-50a1-11e9-9963-4150e1a98f9d.png)

Hi @Fendavo , are you able to tell me where to find this permission option? I have the same issue. Thanks!

**Comment by charlesroper** [comment]
I have the same question. I'd like to remove the download button but I can't see where this permission is set.

@Fendavo Are you saying here in this thread this is what you'd like to see? That is, it's a feature request? I think what you're asking for is an **option** in the plugin settings called "Display Download link in lightbox" which you can toggle off, is that right?
